<a href="https://colab.research.google.com/github/deepbluish/Expanded-Simple-Neural-Network/blob/main/expanded_simple_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

From Dr. Michael J. Garbade's Simple Neural Network but further broken down.

In [177]:
import numpy as np
import matplotlib.pyplot as plt

#Training Data

In [178]:
X_train = np.array([[0,0,1],
                    [1,1,1],
                    [1,0,1],
                    [0,1,1]])

y_train = np.array([[0],
                    [1],
                    [1],
                    [0]])
X_train

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

#Synaptic Weight Matrix

The entire training loop exists only to modify the synaptic weights matrix.  That's it.

In [179]:
np.random.seed(3)
synaptic_weights = 2 * np.random.random((3, 1)) - 1
synaptic_weights

array([[ 0.10159581],
       [ 0.41629565],
       [-0.41819052]])

#One Training Epoch

Make a Prediction in 3 Steps Starting using the X_train data

In [180]:
#1. Create training variable X from X_train matrix and convert to float
X = X_train.astype(float)
X

array([[0., 0., 1.],
       [1., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.]])

In [181]:
#2. Matrix Multiply X by the Synaptic Weight Matrix
X = np.dot(X, synaptic_weights)
X

array([[-0.41819052],
       [ 0.09970093],
       [-0.31659472],
       [-0.00189488]])

In [182]:
#3. Convert X to sigmoid (providing a value between 0 and 1).
X = 1 / (1 + np.exp(-X)) 

# X now is our prediction.  We can compare this with the y matrix and see how close we got.
prediction = X
prediction

array([[0.39694982],
       [0.52490461],
       [0.42150586],
       [0.49952628]])

Comparing the prediction to our target values

In [183]:
y_train # Let's remind ourselves what our target matrix (y_train) look like.

array([[0],
       [1],
       [1],
       [0]])

In [184]:
prediction # Let's remind ourselves of the prediction matrix

array([[0.39694982],
       [0.52490461],
       [0.42150586],
       [0.49952628]])

Calculating the loss

In [185]:
loss = y_train - prediction # How much does this X prediction miss our target values (y_train) by? ...or "Calculate the Loss"
loss

array([[-0.39694982],
       [ 0.47509539],
       [ 0.57849414],
       [-0.49952628]])

Getting the sigmoid derivative of the prediction

In [186]:
#let's remind ourselves of the prediction
prediction

array([[0.39694982],
       [0.52490461],
       [0.42150586],
       [0.49952628]])

In [187]:
sigmoid_derivative = prediction * (1 - prediction) #Get the sigmoid derivative of the prediction
sigmoid_derivative

array([[0.23938066],
       [0.24937976],
       [0.24383867],
       [0.24999978]])

In [188]:
loss_der = loss * sigmoid_derivative
loss_der

array([[-0.09502211],
       [ 0.11847918],
       [ 0.14105924],
       [-0.12488146]])

In [189]:
#Let's look at the X_train matrix but transpose it.
X_train.T

array([[0, 1, 1, 0],
       [0, 1, 0, 1],
       [1, 1, 1, 1]])

In [190]:
adjustments = np.dot(X_train.T, loss_der)
adjustments

array([[ 0.25953842],
       [-0.00640228],
       [ 0.03963485]])

In [191]:
# Let's look at our synaptic weights matrix again.
synaptic_weights

array([[ 0.10159581],
       [ 0.41629565],
       [-0.41819052]])

In [192]:
synaptic_weights += adjustments
synaptic_weights

array([[ 0.36113422],
       [ 0.40989336],
       [-0.37855567]])

This ends the process.  We loop this process over a set period of epochs(iterations) until our synaptic weight matrix is nicely tuned by giving us accurate predictions.

# Reference Functions

In [193]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x)) 

In [194]:
def sigmoid_derivative_func(x):
  return x * (1 - x)

In [195]:
def predict(self, X):
  X = X.astype(float)
  output = sigmoid(np.dot(X, synaptic_weights))
  return output